{
 "title": "LinuxONE LPAR Overview",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPC IFL Usage (%)",
   "type": "timeseries",
   "description": "Total IFL usages of each CPC",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "zhmc_cpc_ifl_processor_usage_ratio{hmc=\"HMC\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Overview",
   "type": "table",
   "description": "The weight defined to each partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "zhmc_partition_ifl_initial_processing_weight{hmc=\"HMC\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zhmc_partition_ifl_processor_count{hmc=\"HMC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition CPU Utilization (%)",
   "type": "timeseries",
   "description": "CPU utilization of each LPAR",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "zhmc_partition_ifl_processor_usage_ratio{hmc=\"HMC\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}