{
 "title": "LinuxONE LPAR Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IBM LinuxONE Infrastructure Monitoring Dashboard\n\nIt helps you to monitor your LinuxONE CPCs and patitions' CPU utilization, partition management overhead, and VM's performance. "
   }
  },
  {
   "title": "LinuxONE CPC Real-time IFL Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zhmc_cpc_ifl_processor_usage_ratio{job=\"zhmc_z17\"} * 100",
     "legendFormat": "{{cpc}}"
    }
   ]
  },
  {
   "title": "CPC IFL Usage (%)",
   "type": "timeseries",
   "description": "Total IFL usages of each CPC",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "zhmc_cpc_ifl_processor_usage_ratio{hmc=\"HMC2\"} * 100",
     "legendFormat": "{{cpc}}"
    }
   ]
  },
  {
   "title": "Partition Overview",
   "type": "table",
   "description": "LCP, weight, and entitlement of each partition",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "zhmc_partition_ifl_processor_count{job=\"zhmc_z17\", cpc=\"BL15\"} and on(partition) zhmc_partition_status_int{value=\"active\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "zhmc_partition_ifl_initial_processing_weight{job=\"zhmc_z17\",cpc=\"BL15\"} and on(partition) zhmc_partition_status_int{value=\"active\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(zhmc_partition_ifl_initial_processing_weight{job=\"zhmc_z17\",cpc=\"BL15\"} and on(partition) zhmc_partition_status_int{value=\"active\"}) by(cpc)",
     "legendFormat": "__auto"
    },
    {
     "expr": "zhmc_cpc_ifl_processor_count{job=\"zhmc_z17\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition CPU Utilization (%)",
   "type": "timeseries",
   "description": "CPU utilization of each LPAR",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "zhmc_partition_processor_usage_ratio{job=\"zhmc_z17\"} * 100",
     "legendFormat": "{{cpc}}-{{partition}}"
    }
   ]
  },
  {
   "title": "LinuxONE CPC mgm/core Ratio - BL15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hyptop_summary_mgm_usage{job=\"hyptop-bz17\"} / hyptop_summary_core_usage{job=\"hyptop-bz17\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LPAR mgm/core Ratio > 10%",
   "type": "timeseries",
   "description": "Display the ration greater than 10% only",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((hyptop_mgm_usage{job=\"hyptop-bz17\"} / hyptop_core_usage{job=\"hyptop-bz17\"}) * 100) > 10",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Hyptop Core% by LPAR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "hyptop_core_usage{job=\"hyptop-bl15\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Hyptop Mgm(%) By LPAR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hyptop_mgm_usage{job=\"hyptop-bz17\"}",
     "legendFormat": "{{system}}"
    }
   ]
  },
  {
   "title": "Hyptop Thread(%) by LPAR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 34 },
   "targets": [
    {
     "expr": "hyptop_the_usage{job=\"hyptop-bz17\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hyptop Total Core(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "hyptop_summary_core_usage{job=\"hyptop-bz17\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Hyptop Total mgm(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "targets": [
    {
     "expr": "hyptop_summary_mgm_usage{job=\"hyptop-bz17\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hyptop Total Thread(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "hyptop_summary_the_usage{job=\"hyptop-bz17\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCP Node CPU Utilization%",
   "type": "timeseries",
   "description": "The average non-idle CPU time rate per instance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OCP Node Steal%",
   "type": "timeseries",
   "description": "Approximated CPU steal% based on the instant rate over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode=\"steal\"}[1m])) * 100) / sum by(instance) (irate(node_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}